<?php

namespace ContainerBqXx3ZC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_FmElfinder_Command_Installer_LazyService extends AppKernelProdContainer
{
    /*
     * Gets the private '.fm_elfinder.command.installer.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.fm_elfinder.command.installer.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('elfinder:install', [], 'Copies elfinder assets to public directory', false, #[\Closure(name: 'fm_elfinder.command.installer', class: 'FM\\ElfinderBundle\\Command\\ElFinderInstallerCommand')] fn (): \FM\ElfinderBundle\Command\ElFinderInstallerCommand => ($container->privates['fm_elfinder.command.installer'] ?? $container->load('getFmElfinder_Command_InstallerService')));
    }
}
