<?php

namespace ContainerBqXx3ZC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_Twig_RuntimeService extends AppKernelProdContainer
{
    /*
     * Gets the private 'knp_menu.twig.runtime' shared service.
     *
     * @return \Knp\Menu\Twig\MenuRuntimeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['knp_menu.helper'] ?? self::getKnpMenu_HelperService($container));

        if (isset($container->privates['knp_menu.twig.runtime'])) {
            return $container->privates['knp_menu.twig.runtime'];
        }

        return $container->privates['knp_menu.twig.runtime'] = new \Knp\Menu\Twig\MenuRuntimeExtension($a, ($container->services['knp_menu.matcher'] ?? self::getKnpMenu_MatcherService($container)), ($container->privates['knp_menu.manipulator'] ??= new \Knp\Menu\Util\MenuManipulator()));
    }
}
