<?php

namespace ContainerBqXx3ZC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Message_Processor_UnsubscribeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.message.processor.unsubscribe' shared service.
     *
     * @return \Mautic\EmailBundle\MonitoredEmail\Processor\Unsubscribe
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.transports'] ?? self::getMailer_TransportsService($container));

        if (isset($container->services['mautic.message.processor.unsubscribe'])) {
            return $container->services['mautic.message.processor.unsubscribe'];
        }

        return $container->services['mautic.message.processor.unsubscribe'] = new \Mautic\EmailBundle\MonitoredEmail\Processor\Unsubscribe($a, ($container->services['mautic.message.search.contact'] ?? $container->load('getMautic_Message_Search_ContactService')), ($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['monolog.logger.mautic'] ?? self::getMonolog_Logger_MauticService($container)), ($container->services['Mautic\\LeadBundle\\Model\\DoNotContact'] ?? self::getDoNotContactService($container)));
    }
}
