<?php

namespace ContainerBqXx3ZC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessUnsubscribeSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\EventListener\ProcessUnsubscribeSubscriber' shared autowired service.
     *
     * @return \Mautic\EmailBundle\EventListener\ProcessUnsubscribeSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.message.processor.unsubscribe'] ?? $container->load('getMautic_Message_Processor_UnsubscribeService'));

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\ProcessUnsubscribeSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\ProcessUnsubscribeSubscriber'];
        }

        return $container->services['Mautic\\EmailBundle\\EventListener\\ProcessUnsubscribeSubscriber'] = new \Mautic\EmailBundle\EventListener\ProcessUnsubscribeSubscriber($a, ($container->services['mautic.message.processor.feedbackloop'] ?? $container->load('getMautic_Message_Processor_FeedbackloopService')));
    }
}
