<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBqXx3ZC\AppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBqXx3ZC/AppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBqXx3ZC.legacy');

    return;
}

if (!\class_exists(AppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBqXx3ZC\AppKernelProdContainer::class, AppKernelProdContainer::class, false);
}

return new \ContainerBqXx3ZC\AppKernelProdContainer([
    'container.build_hash' => 'BqXx3ZC',
    'container.build_id' => '717b59d1',
    'container.build_time' => 1753899849,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBqXx3ZC');
